<?php

namespace App\Controllers;

use Myth\Auth\Controllers\AuthController as MythController;

class AuthController extends MythController
{
    use ViewManager;


    public function __construct()
    {
        parent::__construct();
        $this->initViewManager();
    }

    /**
     * @inheritDoc
     */
    public function login()
    {
        $this->initViewManager();
        return parent::login(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function attemptLogin()
    {
        return parent::attemptLogin(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function logout()
    {
        return parent::logout(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function register()
    {
        return parent::register(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function attemptRegister()
    {
        return parent::attemptRegister(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function forgotPassword()
    {
        return parent::forgotPassword(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function attemptForgot()
    {
        return parent::attemptForgot(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function resetPassword()
    {
        return parent::resetPassword(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function attemptReset()
    {
        return parent::attemptReset(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function activateAccount()
    {
        return parent::activateAccount(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function resendActivateAccount()
    {
        return parent::resendActivateAccount(); // TODO: Change the autogenerated stub
    }


}